=head1 NAME

DbToRia Development

=head2 DESCRIPTION

With the basic structure of DbToRia in place, the featureset is still patchy
at best. The following work packages are largely independent and will lead
to a fully working with a feature set similar to that of Gedafe.

The current project leader (PL) of DbToRia is Tobi Oetiker.

=head2 Implementation Aproach

To ensure implementation consistency and quality, development follows a few simple rules:

=over

=item 1.

Select Task from Task List below. Discuss with PL.

=item 2.

Prepare Implementaiton Concept and Plan. Discuss with PL.

=item 3.

Document. Implement. Test. Send pull request to PL.

=back

=head1 WORK PACKAGES

=head2 Filter builder Widget

Upon clicking the search button in a DbToRia table view, a filter widget
pop-ups which allows to filter the table contents similar to gedafe.
The set of avalable filter operators depend on the choice of database backend.

Status: available

=head2 Direct access URL

The filter and the selected sort order of a view or table is 
reflected in the browser url such that bookmarking will allow to
reopen the view directly.

Status: available

=head2 Configurable Toolbar content

The top row of the dbtoria fe should contains a configurable set toolbar
buttons for directly accessing tables, view or reports. The buttons are
configurable from server side.

Status: available

=head2 AutoForm with setable content

The AutoForm widget can be supplied with a new data set (model)
from the database.

Status: available

=head2 View Form

Rows in read-only tables and views can be opened in a read-only edit form.

Status: available

=head2 Record Switching in Edit Form.

The Edit form gains access-like navigation buttons at the bottom for switching between records without closing the edit form.

Status: available

=head2 Default Values in New Records

The New Record form gets populated with default value from the database.

Status: available

=head2 Pearl Reports Integration

Gedafe Pearl can be used within DbToRia and show up in iframes.

Status: available

=head1 COPYRIGHT

Copyright (c) 2011 by OETIKER+PARTNER AG. All rights reserved.

=head1 LICENSE

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

=head1 AUTHOR

S<Tobias Oetiker E<lt>tobi@oetiker.chE<gt>>,

=head1 HISTORY

 2011-04-010 to initial version

