=head1 NAME

DbToRia Wishlist

=head2 DESCRIPTION

Collect ideas while working/using DbToRiA.

=head2 Frontend

=over

=item

Double click on table row should open edit form.

=item

Loading indicator for longer-running processes (e.g. first opening of
a larger table).

=back

=head1 COPYRIGHT

Copyright (c) 2011 by OETIKER+PARTNER AG. All rights reserved.

=head1 LICENSE

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

=head1 AUTHORS

S<Tobias Oetiker E<lt>tobi@oetiker.chE<gt>>,
S<Fritz Zaucker E<lt>fritz.zaucker@oetiker.chE<gt>>

=head1 HISTORY

 2011-04-012 fz Initial version.
